--swe Spring 2015 group B

DROP SCHEMA IF EXISTS TAAPP CASCADE;
CREATE SCHEMA TAAPP;

SET search_path = TAAPP;


CREATE TABLE Applicant
(
 SSO VARCHAR(20) NOT NULL DEFAULT '',
 LastName VARCHAR(20) NOT NULL,
 FirstName VARCHAR(20) NOT NULL,
 Phone INTEGER NOT NULL,
 Email VARCHAR(40) NOT NULL,
 GPA VARCHAR(4) NOT NULL,
 Graduate BOOLEAN NOT NULL,
 GradDate DATE NOT NULL,
 Graduate BOOLEAN NOT NULL,
 SpeakScore INTEGER,
 PRIMARY KEY(SSO)
);

CREATE TABLE Instructor
(
 SSO VARCHAR(20) NOT NULL DEFAULT '',
 LastName VARCHAR(20) NOT NULL,
 FirstName VARCHAR(20) NOT NULL,
 PRIMARY KEY(SSO)
);

CREATE TABLE ApplicantCourse
(
 SSO VARCHAR(20) NOT NULL DEFAULT '',
 CourseID VARCHAR(10) NOT NULL,
 Rank INTEGER NOT NULL,
 AcceptStatus BOOLEAN NOT NULL DEFAULT '0',
 SectionID VARCHAR(1),
 PRIMARY KEY(SSO, CourseID)
);

CREATE TABLE Course
(
 CourseID VARCHAR(10) NOT NULL,
 CourseName VARCHAR(40) NOT NULL,
 Instruct VARCHAR(20) REFERENCES Instructor(SSO) NOT NULL,
 PRIMARY KEY(CourseID)
);

CREATE TABLE Section
(
 SectionID VARCHAR(1) NOT NULL,
 SectionName VARCHAR(20) NOT NULL,
 TA VARCHAR(20) NOT NULL,
 CourseID VARCHAR(10) REFERENCES Course(CourseID) NOT NULL,
 DateTime DATE NOT NULL,
 PRIMARY KEY(SectionID)
);
